spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/payments
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    generate-ddl: true
    #hibernate:
    #  ddl-auto: create-drop
    open-in-view: false
  data:
    mongodb:
      username: admin
      password: admin
      database: payments
      host: localhost
      port: 27017
      authentication-database: admin
      auto-index-creation: true
  messages:
    basename: exceptions,text
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/realms/training
      client:
        registration:
          github:  # redirect url  http://localhost:8080/login/oauth2/code/github
            client-id: Ov23lioslxWOWdlXtTdc
            client-secret: 604682956900ae22c08d7d12d403cd6427895b61
#          keycloak:
#            client-id: training-client
#            scope:
#              - openid
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8100/realms/training