spring:
  datasource:
    url: jdbc:h2:file:./data/h2-db.db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: ADMIN
management:
  endpoints:
    web:
      exposure:
        include: "*"